<?php
// $Id$

/**
 * @file
 * Test vocabulary import.
 */

/**
 * Implements hook_menu().
 */
function evoc_test_menu() {
  $items['evoc_test/vocabulary_rdf_xml'] = array(
    'title'           => 'RDF/XML vocabulary',
    'description'     => 'Fake RDF/XML vocabulary for import testing.',
    'page callback'   => '_vocabulary_rdf_xml',
    'access callback' => TRUE,
  );
  $items['evoc_test/vocabulary_n3'] = array(
    'title'           => 'N3 vocabulary',
    'description'     => 'Fake N3 vocabulary for import testing.',
    'page callback'   => '_vocabulary_n3',
    'access callback' => TRUE,
  );
  return $items;
}
function _vocabulary_n3() {
  // We fake an n3 vocabulary to feed into the importer.
  drupal_add_http_header('Content-Type', 'text/n3; charset=utf-8');
  print '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix foaf: <http://xmlns.com/foaf/0.1/> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix dc: <http://purl.org/dc/elements/1.1/> .
    @prefix vann: <http://purl.org/vocab/vann/> .
    @prefix rooms: <http://localhost/rdf-contrib/evoc_test/vocabulary_n3#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> .
    @prefix dct: <http://purl.org/dc/terms/> .

    <http://localhost/rdf-contrib/evoc_test/vocabulary_n3> a foaf:Document, owl:Ontology;
        dc:title "Buildings and Rooms Vocabulary";
        dc:description "A simple vocabulary for describing the rooms in a building.";
        vann:preferredNamespaceUri "http://localhost/rdf-contrib/evoc_test/vocabulary_n3#";
        vann:preferredNamespacePrefix "rooms";
        dc:creator rooms:cygri .

    rooms:cygri a foaf:Person;
        foaf:name "Richard Cyganiak";
        foaf:homepage <http://richard.cyganiak.de/>;
        foaf:mbox <mailto:richard.cyganiak@deri.org> .

    <http://localhost/rdf-contrib/evoc_test/vocabulary_n3#Digital%20Enterprise%20Research%20Institute%2C%20NUI%20Galway> a foaf:Organization;
        foaf:member rooms:cygri;
        foaf:name "Digital Enterprise Research Institute, NUI Galway";
        foaf:homepage <http://www.deri.ie/> .

    rooms:Building a rdfs:Class, owl:Class;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Building";
        rdfs:comment "A human-made structure used for sheltering or continuous occupancy.";
        rdfs:subClassOf geo:SpatialThing;
        owl:disjointWith
            foaf:Document,
            foaf:Agent .

    rooms:Room a rdfs:Class, owl:Class;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Room";
        rdfs:comment "A space inside a structure, typically separated from the outside by exterior walls and from other rooms in the same structure by internal walls.";
        rdfs:subClassOf geo:SpatialThing;
        owl:disjointWith
            foaf:Document,
            foaf:Agent .

    rooms:Floor a rdfs:Class, owl:Class;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Floor";
        rdfs:comment "A level part of a building that has a permanent roof. A storey of a building.";
        rdfs:subClassOf geo:SpatialThing;
        owl:disjointWith
            foaf:Document,
            foaf:Agent .

    rooms:FloorSection a rdfs:Class, owl:Class;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Floor Section";
        rdfs:comment "A named part of a floor of a building. Typically used to denote several rooms that are grouped together based on spatial arrangement or use.";
        rdfs:subClassOf geo:SpatialThing;
        owl:disjointWith
            foaf:Agent,
            foaf:Document .

    rooms:Desk a rdfs:Class, owl:Class;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Desk";
        rdfs:comment "A table used in a work or office setting, typically for reading, writing, or computer use.";
        rdfs:subClassOf geo:SpatialThing;
        owl:disjointWith
            foaf:Document,
            foaf:Agent .

    rooms:contains a rdf:Property;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Contains";
        rdfs:comment "The object resource is physically and spatially contained in the subject resource. Being the subject or object of this property implies being a spatial object. Intended for use in the context of buildings, rooms, etc.";
        rdfs:domain geo:SpatialThing;
        rdfs:range geo:SpatialThing;
        rdfs:subPropertyOf dct:hasPart .

    rooms:occupant a rdf:Property;
        rdfs:isDefinedBy <http://localhost/rdf-contrib/evoc_test/vocabulary_n3>;
        rdfs:label "Occupant";
        rdfs:comment "An agent that generally occupies the physical area of the subject resource. Having this property implies being a spatial object. Being the object of this property implies being an agent. Intended for use with buildings, rooms, desks, etc.";
        rdfs:domain geo:SpatialThing;
        rdfs:range foaf:Agent .
    ';
}
/**
 * Menu callback ( see evoc_test_menu() ).
 */
function _vocabulary_rdf_xml() {
  // We fake an RDF/XML vocabulary to feed into the importer.
  drupal_add_http_header('Content-Type', 'application/rdf+xml; charset=utf-8');
  print '<?xml version="1.0" encoding="UTF-8"?>
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:foaf="http://xmlns.com/foaf/0.1/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:vann="http://purl.org/vocab/vann/"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">

    <foaf:Document rdf:about="http://vocab.deri.ie/dcat">
      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>
      <dc:title>Data Catalog Vocabulary (dcat)</dc:title>
      <dc:description>This document defines an RDF vocabulary for the exchange of data catalogs. Its primary purpose is the expression of government data catalogs, such as data.gov or data.gov.uk, in RDF. This is an early draft. We welcome feedback and discussion.</dc:description>
      <vann:preferredNamespaceUri>http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#</vann:preferredNamespaceUri>
      <vann:preferredNamespacePrefix>dcat</vann:preferredNamespacePrefix>

      <dc:creator rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#cygri"/>
      <dc:creator rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#fadmaa"/>
    </foaf:Document>

    <foaf:Person rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#cygri">
      <foaf:name>Richard Cyganiak</foaf:name>
      <foaf:homepage rdf:resource="http://richard.cyganiak.de/"/>
      <foaf:mbox rdf:resource="mailto:richard.cyganiak@deri.org"/>
    </foaf:Person>

    <foaf:Organization rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Digital%20Enterprise%20Research%20Institute%2C%20NUI%20Galway">
      <foaf:member rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#cygri"/>
      <foaf:name>Digital Enterprise Research Institute, NUI Galway</foaf:name>
      <foaf:homepage rdf:resource="http://www.deri.ie/"/>
    </foaf:Organization>

    <foaf:Person rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#fadmaa">
      <foaf:name>Fadi Maali</foaf:name>

      <foaf:mbox rdf:resource="mailto:fadi.maali@deri.org"/>
    </foaf:Person>

    <foaf:Organization rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#DERI%2C%20NUI%20Galway">
      <foaf:member rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#fadmaa"/>
      <foaf:name>DERI, NUI Galway</foaf:name>
      <foaf:homepage rdf:resource="http://deri.ie/"/>
    </foaf:Organization>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#CatalogRecord">
      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Catalog Record</rdfs:label>
      <rdfs:comment>Represents a description of a single dataset in the catalog</rdfs:comment>
    </rdfs:Class>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Catalog">

      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Catalog</rdfs:label>
      <rdfs:comment>A collection of datasets</rdfs:comment>
      <rdfs:subClassOf rdf:resource="http://data.fundacionctic.org/vocab/catalog/datasets#Catalog"/>
    </rdfs:Class>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset">

      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Dataset</rdfs:label>
      <rdfs:comment>A published collection of data</rdfs:comment>
      <rdfs:subClassOf rdf:resource="http://data.fundacionctic.org/vocab/catalog/datasets#Dataset"/>
    </rdfs:Class>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Feed">

      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Feed</rdfs:label>
      <rdfs:comment>represent a feed endpoint that enables access to the data of a dataset</rdfs:comment>
      <rdfs:subClassOf rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>
    </rdfs:Class>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#WebService">

      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Web Service</rdfs:label>
      <rdfs:comment>represents a web service that enables access to the data of a dataset</rdfs:comment>
      <rdfs:subClassOf rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>
    </rdfs:Class>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution">

      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Distribution</rdfs:label>
      <rdfs:comment>Represents a specific available form of a dataset. Each dataset might be available in different forms, these forms might represent different formats of the dataset, different endpoints,... Examples of Distribution include a downloadable CSV file, an XLS file representing the dataset, an RSS endpoint that enables access to the dataset.</rdfs:comment>
    </rdfs:Class>

    <rdfs:Class rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Download">
      <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>

      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>Download</rdfs:label>
      <rdfs:comment>represents a downloadable distribution of a dataset. Use accessURL to point to the downloadable file (should be a direct download link, use Distribution if not)</rdfs:comment>
      <rdfs:subClassOf rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>
    </rdfs:Class>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#themeTaxonomy">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>

      <rdfs:label>theme taxonomy</rdfs:label>
      <rdfs:comment>the knowledge oraganization schema describing themes of datasets within the catalog.</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Catalog"/>
      <rdfs:range rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#dataset">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>

      <rdfs:label>dataset</rdfs:label>
      <rdfs:comment>Connects a catalog to datasets it describes.</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Catalog"/>
      <rdfs:range rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#distribution">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>

      <rdfs:label>distribution</rdfs:label>
      <rdfs:comment>connects a dataset to one of its available distributions</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>
      <rdfs:range rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#dataQuality">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>

      <rdfs:label>data quality</rdfs:label>
      <rdfs:comment>describes the quality of data e.g. precision. This should not be used to describe the data collection characteristics, other more specialized statistical properties can be used instead.</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#theme">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>theme</rdfs:label>

      <rdfs:comment>links a dataset to its theme i.e to its main category. a dataset can have multiple themes.</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>
      <rdfs:range rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
      <rdfs:subPropertyOf rdf:resource="http://purl.org/dc/terms/subject"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#dataDictionary">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>data dictionary</rdfs:label>

      <rdfs:comment>links a dataset to a dictionary that helps interpreting the data.</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#granularity">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>granularity</rdfs:label>
      <rdfs:comment>Describes the level of granularity of data in a dataset. The granularity can be in time, place etc</rdfs:comment>

      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#size">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>size</rdfs:label>
      <rdfs:comment>describe data size e.g. file size</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>

      <rdfs:subPropertyOf rdf:resource="http://purl.org/dc/terms/extent"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#keyword">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>keyword</rdfs:label>
      <rdfs:comment>refers to a tag or keyword describing the dataset</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Dataset"/>

      <rdfs:subPropertyOf rdf:resource="http://purl.org/dc/terms/subject"/>
    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#bytes">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>size in bytes</rdfs:label>
      <rdfs:comment>describe size of resource in bytes</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>

    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#record">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>record</rdfs:label>
      <rdfs:comment>links a catalog to its records</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Catalog"/>
      <rdfs:range rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#CatalogRecord"/>

    </rdf:Property>

    <rdf:Property rdf:about="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#accessURL">
      <rdfs:isDefinedBy rdf:resource="http://vocab.deri.ie/dcat"/>
      <rdfs:label>access URL</rdfs:label>
      <rdfs:comment>describes availability of a dataset. This can be a direct download link, an HTML page containing a link to the actual data, Feed, Web Service etc. the semantic is determined by its domain (Distribution, Feed, WebService, Download).</rdfs:comment>
      <rdfs:domain rdf:resource="http://localhost/rdf-contrib/evoc_test/vocabulary_rdf_xml#Distribution"/>
    </rdf:Property>

  </rdf:RDF>';
return;
}
